# Generated by Django 5.2.6 on 2025-09-14 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_alter_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id_user',
        ),
    ]
