# Generated by Django 5.2.6 on 2025-09-14 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_profile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
    ]
