# Generated by Django 5.2.6 on 2025-09-14 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_usersetting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date_added',
            new_name='created_at',
        ),
    ]
