# Generated by Django 5.2.6 on 2025-09-15 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0024_message_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
